# Generated by Django 4.1.4 on 2022-12-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_product_category'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='favorite',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
