# Generated by Django 4.1.4 on 2023-01-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Shopper',
        ),
    ]
