# Generated by Django 4.1.4 on 2022-12-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=2)),
                ('order', models.ManyToManyField(to='store.cart')),
                ('product', models.ManyToManyField(to='store.product')),
            ],
        ),
    ]
