# Generated by Django 4.1.4 on 2022-12-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='order',
        ),
        migrations.RemoveField(
            model_name='test',
            name='product',
        ),
        migrations.AddField(
            model_name='test',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
