# Generated by Django 4.1.3 on 2022-12-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='orders',
        ),
    ]
