# Generated by Django 4.1.4 on 2022-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_test_order_remove_test_product_test_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
