# Generated by Django 4.1.4 on 2022-12-20 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_cart_product_remove_cart_quantity_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
