# Generated by Django 4.1.4 on 2022-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderdetails_total_alter_orderdetails_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_valided',
            field=models.BooleanField(default=False),
        ),
    ]
