# Generated by Django 4.1.4 on 2022-12-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_is_valided'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='carrier',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
