# Generated by Django 4.1.4 on 2023-05-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_cart_ordered_remove_cart_ordered_date_and_more'),
        ('store', '0015_alter_order_order_alter_orderproduct_product_shopper'),
    ]

    operations = [
    ]
