# Generated by Django 4.1.4 on 2023-05-15 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_merge_20230513_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='carrier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
